import { montserrat, poppins } from '@/utils/fonts';
import "./globals.css";

export const metadata = {
  title: "RMS Marketing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
		<html lang='en'>
			<body
				className={`${poppins} ${montserrat} font-poppins font-normal text-sm`}>
				{children}
			</body>
		</html>
  );
}
